development:
  adapter: mysql2
  encoding: utf8
  database: RoR_development
  username: Jeffer
  password: debian123
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: RoR_test
  username: Jeffer
  password: debian123
  host: localhost
  port: 3306